---

driver:
  name: vagrant

provisioner:
  name: puppet_apply
  manifests_path: manifests
  modules_path: modules
  hiera_data_path: hieradata
  manifest: site.pp
  test_repo_uri: "https://github.com/TelekomLabs/tests-ssh-hardening.git"

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box

- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

- name: centos-6.5
  driver_config:
     box: opscode-centos-6.5
     box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box

- name: oracle-6.4
  driver_config:
    box: oracle-6.4
    box_url: https://dl.dropbox.com/sh/yim9oyqajopoiqs/G-XIEmQJMb/oracle64-64.box

- name: debian-squezze-6
  driver_config:
    box: debian-squezze-6
    box_url: http://public.sphax3d.org/vagrant/squeeze64.box

- name: debian-wheezy-7
  driver_config:
    box: debian-wheezy-7
    box_url: https://dl.dropboxusercontent.com/s/cd583cuf0mbcix7/debian-wheezy-64-chef.box

suites:
  - name: default

